# Generated by Django 5.2 on 2025-04-03 08:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=10, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('nationalId', models.CharField(max_length=50, null=True, unique=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('maritalStatus', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=50)),
                ('department', models.CharField(default='System', max_length=50)),
                ('employee_type', models.CharField(default='Unspecified', max_length=50)),
                ('leave_days', models.IntegerField(default=0)),
                ('contractFrom', models.DateField(blank=True, null=True)),
                ('contractTo', models.DateField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('frequency', models.CharField(default='monthly', max_length=50)),
                ('bankName', models.CharField(blank=True, max_length=100)),
                ('bankAccount', models.CharField(blank=True, max_length=50)),
                ('pensionFund', models.CharField(blank=True, max_length=100)),
                ('nssaNumber', models.CharField(blank=True, max_length=50)),
                ('zimraTaxNumber', models.CharField(blank=True, max_length=50)),
                ('payeNumber', models.CharField(blank=True, max_length=50)),
                ('aidsLevyNumber', models.BooleanField(default=True)),
                ('isActive', models.BooleanField(default=True)),
                ('emegencyContactName', models.CharField(blank=True, max_length=100)),
                ('emegencyContactNumber', models.CharField(blank=True, max_length=15)),
                ('emegencyContactRelationship', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ZiGRateToUSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('rate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employeeid', models.CharField(blank=True, max_length=10, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('department', models.CharField(default='System', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('contractFrom', models.DateField(blank=True, null=True)),
                ('contractTo', models.DateField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseSalaryUSD', models.CharField(max_length=100)),
                ('baseSalaryZiG', models.CharField(max_length=100)),
                ('period', models.DateField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employees')),
                ('exchangeRate', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='erp.zigratetousd')),
            ],
        ),
    ]
