# Generated by Django 5.2 on 2025-04-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='nationalId',
            new_name='nationalid',
        ),
    ]
